version: "1"

databases:
  - name: devClicker-db
    databaseName: dbclickerdb
    user: dbclickerdb_user
    plan: free
    region: oregon
    ipAllowList:
      - source: 0.0.0.0/0
        description: everywhere
    postgresMajorVersion: "17"

services:

- type: web
  name: devclicker
  runtime: python
  repo: https://github.com/alissonsz1/Clicker-Project
  branch: main
  plan: free
  envVars:
  - key: DJANGO_SUPERUSER_USERNAME
    sync: false
  - key: DJANGO_SUPERUSER_PASSWORD
    sync: false
  - key: DJANGO_SUPERUSER_EMAIL
    sync: false
  - key: REDIS_PORT
    sync: false
  - key: REDIS_HOST
    sync: false
  - key: CSRF_TRUSTED_ORIGINS
    sync: false
  - key: DJANGO_SECRET_KEY
    sync: false
  - key: DJANGO_ALLOWED_HOST
    sync: false
  - key: DATABASE_URL
    sync: false
  - key: DEBUG
    sync: false
  region: oregon
  buildCommand: pip install -r requirements.txt
  startCommand: |
    python manage.py makemigrations &&
    python manage.py migrate &&
    python manage.py flush --no-input &&
    python manage.py createadmin &&
    python manage.py collectstatic --noinput &&
    daphne -b 0.0.0.0 -p $PORT devClicker.asgi:application
  autoDeployTrigger: commit

- type: keyvalue

  name: devclicker-rediskey

  plan: free

  region: oregon

  maxmemoryPolicy: allkeys-lru

  ipAllowList:

  - source: 177.50.42.248/32

    description: Webcaique (sidraocaique@gmail.com)