# Generated by Django 5.2.4 on 2025-08-07 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0007_alter_companies_lscount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companies',
            name='lsCount',
            field=models.BigIntegerField(default='0'),
        ),
    ]
