# Generated by Django 5.2.4 on 2025-08-07 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0008_alter_companies_lscount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companies',
            name='structures',
        ),
        migrations.RemoveField(
            model_name='companies',
            name='upgrades',
        ),
    ]
