# Generated by Django 5.2.4 on 2025-08-08 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0009_remove_companies_structures_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companies',
            name='lsCount',
            field=models.TextField(default='0'),
        ),
    ]
