# Generated by Django 5.2.4 on 2025-08-08 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0010_alter_companies_lscount'),
    ]

    operations = [
        migrations.AddField(
            model_name='companies',
            name='lsHighest',
            field=models.TextField(default='0'),
        ),
    ]
