# Generated by Django 5.2.4 on 2025-08-21 23:33

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0011_companies_lshighest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companies',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
